# Generated by Django 2.2.4 on 2021-05-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pid',
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name='fillquestion',
            name='level',
            field=models.CharField(choices=[('4', 'hard'), ('1', 'easy'), ('3', 'difficult'), ('2', 'normal'), ('5', 'hell')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='level',
            field=models.CharField(choices=[('4', 'hard'), ('1', 'easy'), ('3', 'difficult'), ('2', 'normal'), ('5', 'hell')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('4', 'hard'), ('1', 'easy'), ('3', 'difficult'), ('2', 'normal'), ('5', 'hell')], max_length=10, verbose_name='难度等级'),
        ),
    ]
