# Generated by Django 2.2.4 on 2021-05-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210507_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=True, to='student.Paper'),
        ),
        migrations.AlterField(
            model_name='fillquestion',
            name='level',
            field=models.CharField(choices=[('5', 'hell'), ('3', 'difficult'), ('2', 'normal'), ('4', 'hard'), ('1', 'easy')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='level',
            field=models.CharField(choices=[('5', 'hell'), ('3', 'difficult'), ('2', 'normal'), ('4', 'hard'), ('1', 'easy')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('5', 'hell'), ('3', 'difficult'), ('2', 'normal'), ('4', 'hard'), ('1', 'easy')], max_length=10, verbose_name='难度等级'),
        ),
    ]
