# Generated by Django 2.2.4 on 2021-05-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210509_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillquestion',
            name='order',
            field=models.IntegerField(default=1, verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='fillquestion',
            name='level',
            field=models.CharField(choices=[('3', 'difficult'), ('5', 'hell'), ('1', 'easy'), ('4', 'hard'), ('2', 'normal')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='level',
            field=models.CharField(choices=[('3', 'difficult'), ('5', 'hell'), ('1', 'easy'), ('4', 'hard'), ('2', 'normal')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('3', 'difficult'), ('5', 'hell'), ('1', 'easy'), ('4', 'hard'), ('2', 'normal')], max_length=10, verbose_name='难度等级'),
        ),
    ]
