# Generated by Django 2.2.4 on 2021-05-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210511_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillquestion',
            name='level',
            field=models.CharField(choices=[('4', 'hard'), ('2', 'normal'), ('3', 'difficult'), ('1', 'easy'), ('5', 'hell')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='fillquestion',
            name='order',
            field=models.IntegerField(choices=[(1, '空格输入有序'), (2, '空格输入无序')], default=1, verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='level',
            field=models.CharField(choices=[('4', 'hard'), ('2', 'normal'), ('3', 'difficult'), ('1', 'easy'), ('5', 'hell')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('4', 'hard'), ('2', 'normal'), ('3', 'difficult'), ('1', 'easy'), ('5', 'hell')], max_length=10, verbose_name='难度等级'),
        ),
    ]
