# Generated by Django 2.2.4 on 2021-05-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210511_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='overtime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fillquestion',
            name='level',
            field=models.CharField(choices=[('2', 'normal'), ('5', 'hell'), ('1', 'easy'), ('4', 'hard'), ('3', 'difficult')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='level',
            field=models.CharField(choices=[('2', 'normal'), ('5', 'hell'), ('1', 'easy'), ('4', 'hard'), ('3', 'difficult')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('2', 'normal'), ('5', 'hell'), ('1', 'easy'), ('4', 'hard'), ('3', 'difficult')], max_length=10, verbose_name='难度等级'),
        ),
    ]
