# Generated by Django 2.2.4 on 2021-05-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210513_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillquestion',
            name='level',
            field=models.CharField(choices=[('4', 'hard'), ('1', 'easy'), ('2', 'normal'), ('3', 'difficult'), ('5', 'hell')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Paper'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='level',
            field=models.CharField(choices=[('4', 'hard'), ('1', 'easy'), ('2', 'normal'), ('3', 'difficult'), ('5', 'hell')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='overtime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('4', 'hard'), ('1', 'easy'), ('2', 'normal'), ('3', 'difficult'), ('5', 'hell')], max_length=10, verbose_name='难度等级'),
        ),
    ]
