# Generated by Django 2.2.4 on 2021-05-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210514_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillquestionanswer',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='rate',
        ),
        migrations.AddField(
            model_name='fillquestionanswer',
            name='all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fillquestionanswer',
            name='right',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='right',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fillquestion',
            name='level',
            field=models.CharField(choices=[('2', 'normal'), ('1', 'easy'), ('4', 'hard'), ('3', 'difficult'), ('5', 'hell')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='level',
            field=models.CharField(choices=[('2', 'normal'), ('1', 'easy'), ('4', 'hard'), ('3', 'difficult'), ('5', 'hell')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('2', 'normal'), ('1', 'easy'), ('4', 'hard'), ('3', 'difficult'), ('5', 'hell')], max_length=10, verbose_name='难度等级'),
        ),
    ]
