# Generated by Django 2.2.4 on 2021-05-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210516_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillquestion',
            name='level',
            field=models.CharField(choices=[('4', 'hard'), ('5', 'hell'), ('1', 'easy'), ('3', 'difficult'), ('2', 'normal')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='fillquestionanswer',
            name='right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='level',
            field=models.CharField(choices=[('4', 'hard'), ('5', 'hell'), ('1', 'easy'), ('3', 'difficult'), ('2', 'normal')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('4', 'hard'), ('5', 'hell'), ('1', 'easy'), ('3', 'difficult'), ('2', 'normal')], max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='right',
            field=models.IntegerField(default=0),
        ),
    ]
